# Generated by Django 3.2.4 on 2021-09-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dizimista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista_Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='Ano')),
                ('dizimista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dizimista_controle', to='dizimista.dizimista', verbose_name='Dizimista-Controle')),
            ],
            options={
                'verbose_name': 'Dizimista-Controle',
                'verbose_name_plural': 'Dizimistas-Controle',
                'ordering': ['dizimista'],
            },
        ),
    ]
