# Generated by Django 3.2.4 on 2021-09-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimista_controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista_controle',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default=0, max_length=2, verbose_name='Mês'),
            preserve_default=False,
        ),
    ]
