# Generated by Django 3.2.4 on 2021-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome do Missionário')),
            ],
            options={
                'verbose_name': 'Missionário',
                'verbose_name_plural': 'Missionários',
                'ordering': ['nome'],
            },
        ),
    ]
