# Generated by Django 3.2.4 on 2021-09-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_missionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionario',
            options={'ordering': ['nome'], 'verbose_name': 'Missionário', 'verbose_name_plural': 'Missionários'},
        ),
    ]
