# Generated by Django 3.2.4 on 2021-09-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_dizimista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle_Dizimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='Ano')),
                ('mes', models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, verbose_name='Mês')),
                ('dizimista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dizimista_controle', to='cad_dizimista.dizimista', verbose_name='Dizimista-Controle')),
            ],
            options={
                'verbose_name': 'Controle-Dízimo',
                'verbose_name_plural': 'Controle-Dízimos',
                'ordering': ['ano', 'mes'],
            },
        ),
    ]
