# Generated by Django 3.2.4 on 2021-09-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_missionario', '0002_alter_missionario_options'),
        ('cad_dizimista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='missionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cad_missionario', to='cad_missionario.missionario', verbose_name='Missionario'),
        ),
    ]
