# Generated by Django 3.2.4 on 2021-09-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidade', '0002_auto_20210923_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome do Dizimista')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidade', to='comunidade.comunidade', verbose_name='Comunidade')),
            ],
            options={
                'verbose_name': 'Dizimista',
                'verbose_name_plural': 'Dizimistas',
                'ordering': ['nome'],
            },
        ),
    ]
